In [1]:
import sys
sys.path.append("..")
import pandas as pd
import json
import urllib.request
from IPython.display import clear_output
import countries
from dataframe import *

In [2]:
# Load entire WB ASPIRE database into a dataframe
aspire = pd.read_csv("aspire_EXCEL.csv")

In [3]:
aspire_poorest = aspire[aspire['Indicator Name'].str.contains('poorest')]

In [4]:
aspire_poorest_all = aspire_poorest[aspire_poorest['Indicator Name'].str.contains('All Social Protection')]

In [5]:
cov = aspire[aspire['Indicator Name'] == 'Coverage in poorest quintile (%) -All Social Protection and Labor']

In [6]:
cov_ldcs = cov[cov['Country Name'].isin(countries.ldcs_all_names)]

In [7]:
cov_ldcs.to_csv("cov_all_social_protection_poorest_q_ldcs.csv")

In [8]:
cov_ldcs_latest = get_latest_values(
    data = cov_ldcs,
    date_field = "year", 
    value_field = 'value', 
    name_field = "Country Name")

In [9]:
# Remove lines that includes "Indicator Code" in the year
cov_ldcs_latest = cov_ldcs_latest[cov_ldcs_latest.year != 'Indicator Code' ]
cov_ldcs_latest

                    Country Name  year     value
39096                Afghanistan  2011   12.4666
63592                 Bangladesh  2010   25.5303
72778                      Benin  2003   3.60006
75840                     Bhutan  2012   4.12246
94212               Burkina Faso  2014   1.82554
103398                  Cambodia  2013   0.91514
109522  Central African Republic  2008  0.659178
112584                      Chad  2011  0.725241
124832                   Comoros  2004  0.885111
143204                  Djibouti  2012   35.6908
167700                  Ethiopia  2010   16.2103
176886               Gambia, The  1998   1.35068
235064                  Kiribati  2006   4.84024
247312                   Lao PDR  2007  0.295753
256498                   Lesotho  2014   64.0594
259560                   Liberia  2007   66.0574
268746                Madagascar  2010    1.2073
271808                    Malawi  2013   42.4531
280994                      Mali  2009    0.5587
287118                Mauritania  2014   47.4608
311614                Mozambique  2008    8.2441
314676                   Myanmar  2009  0.783487
320800                     Nepal  2010   49.0725
326924                     Niger  2011   2.80711
363668                    Rwanda  2010    50.405
366730                     Samoa  2008   31.8109
375916                   Senegal  2011   11.0088
385102              Sierra Leone  2011   34.5724
394288           Solomon Islands  2005   1.11416
400412               South Sudan  2009   3.36707
415722                     Sudan  2009    13.101
431032                  Tanzania  2012   22.1222
437156               Timor-Leste  2011   41.3972
440218                      Togo  2011         0
455528                    Uganda  2012   76.1488
483086                    Zambia  2010   1.19382

In [44]:
cov_ldcs_latest['value']= pd.to_numeric(cov_ldcs_latest['value'])
cov_ldcs_latest['year']= pd.to_numeric(cov_ldcs_latest['year'])

In [45]:
pop = pd.read_csv("wpp2015_total_population_both_sexes.csv", encoding = 'ISO-8859-1')

In [46]:
pop_ldcs = pop[pop['Major area, region, country or area *'].isin(countries.ldcs_all_names)]

In [47]:
# Rename columns
pop_ldcs = pop_ldcs.rename( columns = {'Major area, region, country or area *' : "Country"})

In [48]:
# We have to create the index to be 
# able to search by label
pop_ldcs = pop_ldcs.set_index("Country")

In [49]:
pop_ldcs.loc["Burundi", "2015"]

11178.92

In [50]:
p = []
for index, row in cov_ldcs_latest.iterrows():
    p.append ( pd.to_numeric(pop_ldcs.loc[row['Country Name'], row['year']]))

TypeError: cannot do label indexing on <class 'pandas.indexes.base.Index'> with these indexers [2011] of <class 'int'>

In [51]:
cov_ldcs_latest['population'] = p

ValueError: Length of values does not match length of index

In [52]:
cov_ldcs_latest

                    Country Name  year      value  population
39096                Afghanistan  2011  12.466566    28809.17
63592                 Bangladesh  2010  25.530313   151616.78
72778                      Benin  2003   3.600064     7665.68
75840                     Bhutan  2012   4.122461      743.71
94212               Burkina Faso  2014   1.825540    17589.20
103398                  Cambodia  2013   0.915140    15078.56
109522  Central African Republic  2008   0.659178     4280.41
112584                      Chad  2011   0.725241    12298.51
124832                   Comoros  2004   0.885111      603.87
143204                  Djibouti  2012  35.690794      853.07
167700                  Ethiopia  2010  16.210311    87561.81
176886               Gambia, The  1998   1.350679     1159.00
235064                  Kiribati  2006   4.840237       94.26
247312                   Lao PDR  2007   0.295753     5939.63
256498                   Lesotho  2014  64.059362     2109.20
259560                   Liberia  2007  66.057374     3522.34
268746                Madagascar  2010   1.207300    21079.53
271808                    Malawi  2013  42.453146    16190.13
280994                      Mali  2009   0.558700    14694.57
287118                Mauritania  2014  47.460808     3969.63
311614                Mozambique  2008   8.244096    22994.87
314676                   Myanmar  2009   0.783487    51369.73
320800                     Nepal  2010  49.072532    26875.91
326924                     Niger  2011   2.807105    16946.49
363668                    Rwanda  2010  50.404994    10293.67
366730                     Samoa  2008  31.810875      183.44
375916                   Senegal  2011  11.008832    13357.00
385102              Sierra Leone  2011  34.572356     5908.91
394288           Solomon Islands  2005   1.114163      469.31
400412               South Sudan  2009   3.367066     9623.18
415722                     Sudan  2009  13.100951    35297.30
431032                  Tanzania  2012  22.122178    48645.71
437156               Timor-Leste  2011  41.397244     1077.60
440218                      Togo  2011   0.000000     6566.18
455528                    Uganda  2012  76.148753    35400.62
483086                    Zambia  2010   1.193820    13917.44

In [53]:
cov_ldcs_latest_2009 = cov_ldcs_latest[cov_ldcs_latest['year'] > 2008]

In [55]:
len(cov_ldcs_latest_2009)

26

In [56]:
"""
    Calculates weigthed average

    Parameters
    ----------
    data : Pandas dataframe
        Dataframe with data to be wieghted
    weight : Pandas dataframe
        Dataframe containing weight values
    data_field: string
        Name of field with data to weight
    weight_field: string
        Name of field with data for weighting
    name_weighted_column: string
        Name of column that will be created with weighted values
        
    Returns
    -------
    object
        Return a PANDAS dataframe with an additional column 
        containing weighted values

    """
def weighted_average(**kwargs):
    
    # Work with a copy of the original dataset so when we add
    # the column with the weights we do not get a warning
    data = kwargs['data'].copy()
    # Dataframe containing values for weigthing. It can be the same
    # than the dataframe with the data
    weight = kwargs['weight']
    # Sum all weight values
    sum_valid_weight = weight[kwargs['weight_field']].sum()
    # Calculate weigthed average
    c = data[kwargs['data_field']] * (weight[kwargs['weight_field']] / sum_valid_weight)
    # Add a column with weigthed values to the dataframe
    data[kwargs['name_weighted_column']] = c
    # Return dataframe with weighted values
    
    return data

In [59]:
weighted = weighted_average(data=cov_ldcs_latest_2009, weight=cov_ldcs_latest_2009, data_field = "value", weight_field = "population", name_weighted_column="weight")

In [63]:
weighted.weight.sum()

20.66298601744224